# Generated by Django 4.1.3 on 2022-12-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cartproduct_delete_bascket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
